arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_joint_01
    - arm_joint_02
    - arm_joint_03
    - arm_joint_04
    - cluedo_link_joint
  gains:
    arm_joint_01:
      p: 30 
      d: 0
      i: 0
      i_clamp: 0 #1.5
    arm_joint_02:
      p: 60
      d: 0
      i: 0
      i_clamp: 0 #1.5
    arm_joint_03:
      p: 50
      d: 0
      i: 0
      i_clamp: 0 #1.5
    arm_joint_04:
      p: 30
      d: 0
      i: 0
      i_clamp: 0 #1.5
    cluedo_link_joint:
      p: 30
      d: 0
      i: 0
      i_clamp: 1.5